### ISSUE TITLE
大佬，请问下mpc中求ref_delta的公式理解

### ISSUE THREAD

**Issue by gosundy** [CHH3213/chhRobotics#1]

**Comment by gosundy** [comment]
# 参考控制量[v,delta]         ref_delta = math.atan2(L*k, 1)

**Comment by gosundy** [comment]
# 参考控制量[v,delta]        
 ref_delta = math.atan2(L*k, 1)

**Comment by CHH3213** [comment]
k是曲率，满足曲率半径R=1/k，控制量delta它满足tan delta=L/R=kL。所以可以通过反正切得到控制量的表达式，详情可进一步查看【【自动驾驶】车辆运动学模型 - CSDN App】http://t.csdnimg.cn/FdGWd的以后轴为中心建立的运动学模型
